=== dgheo5083/scbk-process2/50176-process-api-config-lib/src/main/resources/schema/holiday-definition.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

  <!-- 루트: holiday-definition -->
  <xs:element name="holiday-definition">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="holiday" type="HolidayType" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="year" type="xs:string" use="required"/>
      <xs:attribute name="useYn" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>

  <!-- holiday 항목 -->
  <xs:complexType name="HolidayType">
    <xs:attribute name="date" type="xs:string" use="required"/>
    <xs:attribute name="description" type="xs:string" use="required"/>
  </xs:complexType>

</xs:schema>

=== dgheo5083/scbk-process2/50176-process-api-config-lib/src/main/resources/config/holiday/holiday-2026.xml
<?xml version="1.0" encoding="UTF-8"?>
<holiday-definition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:noNamespaceSchemaLocation="../../schema/holiday-definition.xsd"
                    year="2026"
                    useYn="Y">
  <holiday date="20260505" description="어린이날"/>
  <holiday date="20260525" description="부처님오신날 대체공휴일"/>
  <holiday date="20260606" description="현충일"/>
  <holiday date="20260815" description="광복절"/>
  <holiday date="20260912" description="추석"/>
  <holiday date="20260913" description="추석"/>
  <holiday date="20261003" description="개천절"/>
  <holiday date="20261009" description="한글날"/>
  <holiday date="20261225" description="크리스마스"/>
</holiday-definition>
